/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Testing_pageRouteImport } from './routes/testing_page'
import { Route as IndexRouteImport } from './routes/index'

const Testing_pageRoute = Testing_pageRouteImport.update({
  id: '/testing_page',
  path: '/testing_page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testing_page': typeof Testing_pageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testing_page': typeof Testing_pageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/testing_page': typeof Testing_pageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/testing_page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/testing_page'
  id: '__root__' | '/' | '/testing_page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Testing_pageRoute: typeof Testing_pageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing_page': {
      id: '/testing_page'
      path: '/testing_page'
      fullPath: '/testing_page'
      preLoaderRoute: typeof Testing_pageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Testing_pageRoute: Testing_pageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
