/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SysfetchRouteImport } from './routes/sysfetch'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SecretRouteImport } from './routes/secret'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as R88x31RouteImport } from './routes/88x31'
import { Route as IndexRouteImport } from './routes/index'

const SysfetchRoute = SysfetchRouteImport.update({
  id: '/sysfetch',
  path: '/sysfetch',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const R88x31Route = R88x31RouteImport.update({
  id: '/88x31',
  path: '/88x31',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/88x31': typeof R88x31Route
  '/blogs': typeof BlogsRoute
  '/interests': typeof InterestsRoute
  '/projects': typeof ProjectsRoute
  '/secret': typeof SecretRoute
  '/skills': typeof SkillsRoute
  '/sysfetch': typeof SysfetchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/88x31': typeof R88x31Route
  '/blogs': typeof BlogsRoute
  '/interests': typeof InterestsRoute
  '/projects': typeof ProjectsRoute
  '/secret': typeof SecretRoute
  '/skills': typeof SkillsRoute
  '/sysfetch': typeof SysfetchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/88x31': typeof R88x31Route
  '/blogs': typeof BlogsRoute
  '/interests': typeof InterestsRoute
  '/projects': typeof ProjectsRoute
  '/secret': typeof SecretRoute
  '/skills': typeof SkillsRoute
  '/sysfetch': typeof SysfetchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/88x31'
    | '/blogs'
    | '/interests'
    | '/projects'
    | '/secret'
    | '/skills'
    | '/sysfetch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/88x31'
    | '/blogs'
    | '/interests'
    | '/projects'
    | '/secret'
    | '/skills'
    | '/sysfetch'
  id:
    | '__root__'
    | '/'
    | '/88x31'
    | '/blogs'
    | '/interests'
    | '/projects'
    | '/secret'
    | '/skills'
    | '/sysfetch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R88x31Route: typeof R88x31Route
  BlogsRoute: typeof BlogsRoute
  InterestsRoute: typeof InterestsRoute
  ProjectsRoute: typeof ProjectsRoute
  SecretRoute: typeof SecretRoute
  SkillsRoute: typeof SkillsRoute
  SysfetchRoute: typeof SysfetchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sysfetch': {
      id: '/sysfetch'
      path: '/sysfetch'
      fullPath: '/sysfetch'
      preLoaderRoute: typeof SysfetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/88x31': {
      id: '/88x31'
      path: '/88x31'
      fullPath: '/88x31'
      preLoaderRoute: typeof R88x31RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R88x31Route: R88x31Route,
  BlogsRoute: BlogsRoute,
  InterestsRoute: InterestsRoute,
  ProjectsRoute: ProjectsRoute,
  SecretRoute: SecretRoute,
  SkillsRoute: SkillsRoute,
  SysfetchRoute: SysfetchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
